language: php
php:
  - "5.4"

# Install pip using apt
addons:
  apt:
    packages:
    - python-pip
    - python-virtualenv
    - git
    - mysql-server
    - apache2
    - dpkg-dev
    - php5
    - php5-mysql
    - php5-gd
    - php5-dev
    - php5-curl
    - php5-cli
    - unzip
    - wget
    - time

before_install:
  - ./download_phab.sh

# Install dependencies using pip
install:
  - virtualenv venv
  - source venv/bin/activate
  - pip install autopep8
  - pip install docformatter
  - pip install flake8
  - pip install nose
  # TODO: Change this to 'pip install pycheker' once pycheker starts working
  # with pip. pip install of pycheker is broken at the moment.
  - pip install http://sourceforge.net/projects/pychecker/files/pychecker/0.8.19/pychecker-0.8.19.tar.gz/download
  - pip install pylint
  - pip install snakefood

before_script:
  - git config --global user.email "tests@phab.test"
  - git config --global user.name "Test User"
  # TODO: Make the following commands run without sudo. At the time of writing
  # this script, Travis CI was not automatically picking up virtual host config
  # hence we had to use sudo instead.
  - sudo cp build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo a2enmod rewrite
  - sudo service apache2 restart

# command to run tests
script:
  # - ./static_tests.sh
  - ./unit_tests.sh

notifications:
    email: false
