sudo: false

language: python
python:
  - "2.7"

# Install pip using apt
addons:
  apt:
    packages:
    - python-pip
    - git
    - mysql-server
    - apache2
    - dpkg-dev
    - php5
    - php5-mysql
    - php5-gd
    - php5-dev
    - php5-curl
    - php-apc
    - php5-cli
    - php5-json
    - unzip
    - wget

# Install dependencies using pip
install:
  - pip install autopep8
  - pip install docformatter
  - pip install flake8
  - pip install nose
  # TODO: Change this to 'pip install pycheker' once pycheker starts working
  # with pip. pip install of pycheker is broken at the moment.
  - pip install http://sourceforge.net/projects/pychecker/files/pychecker/0.8.19/pychecker-0.8.19.tar.gz/download
  - pip install pylint
  - pip install snakefood

# command to run tests
script: ./static_tests.sh

notifications:
    email: false
